### ISSUE TITLE
Failed to compile because of DTypePointer

### ISSUE THREAD

**Issue by jgsimard** [YichengDWu/matmul.mojo#1]
Hi,
it failed to compile because it was using DTypePointer which was removed recently in MAX (https://github.com/modularml/mojo/blob/634387c441dd635b9c84492f67d93e8db19198fb/docs/changelog.md?plain=1#L540) . I commented 
`@always_inline("nodebug")
    fn __init__(inout self, data: DTypePointer[Type], owned layout: Layout):
        self.data = UnsafePointer[Scalar[Type],]._from_dtype_ptr(data)
        self.layout = layout
`
then it works fine.
Amazing work!

**Comment by YichengDWu** [comment]
This should be fixed now as I remove the DTypePointer. It's never used. Thanks for reporting!
